services:
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client/dist:/app/client/dist
    environment:
      - NODE_ENV=production
    command: pnpm --filter client run build

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge