name: Deploy on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted label-test

    steps:
      # 1. 레포지토리 클론
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Docker Compose로 서비스 빌드 및 재시작
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Deploy Docker Images
        run: |
          # docker-compose로 배포
          docker-compose up -d --build

      # 3. Clean up Old Images
      - name: Remove Dangling Images
        run: docker image prune -f
